# Generated by Django 3.0.6 on 2020-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(default='default.jpg', upload_to='services_pics')),
                ('preco', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
