# Generated by Django 3.0.6 on 2020-06-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
